version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 20040:80
    volumes:
      - .:/app
      - ./logs:/app/logs
    # environment:
